### ISSUE TITLE
css 

### ISSUE THREAD

**Issue by Anichki** [Anichki/mixeiltkavadze#1]
შექმენი scc ფაილი რაიმე სახელით, ჩადე scc ფოლდერში და html-ში სწორად გაუწერე href, ანუ საიდან უნდა აიღოს css ფაილი.

ეს დაგვჭირდება იმისთვის, რომ მივცეთ სახე ვებგვერდს. შენ ახლა ჩონჩხი ააწყე ძალიან კარგად და ახლა გარესახე("მაკიაჟი :)") უნდა გავუკეთოთ, თუ როგორ გამოიყურებოდეს ეს ელემენტები.

**Comment by tkavadze** [comment]
შექმნილია შესაბამისი Pull Request.
